# Generated by Django 4.2.3 on 2023-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_createtodo_todo_createtodo_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='expectedTime',
            field=models.TimeField(),
        ),
    ]
