# Generated by Django 4.2.3 on 2023-09-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_createtodo_expecteddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='createdDT',
        ),
    ]
