# Generated by Django 4.2.3 on 2023-09-29 23:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_createtodo_createddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtodo',
            name='createdDT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(verbose_name=datetime.date(2023, 9, 30)),
        ),
    ]
