# Generated by Django 4.2.3 on 2023-09-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_createtodo_expecteddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedDate',
        ),
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedTime',
        ),
    ]
