# Generated by Django 4.2.3 on 2023-09-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_createtodo_expecteddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(default='2000-1-12'),
        ),
        migrations.AddField(
            model_name='createtodo',
            name='expectedTime',
            field=models.TimeField(default='12:12'),
        ),
    ]
