# Generated by Django 4.2.3 on 2023-09-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_createtodo_expectedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedDate',
        ),
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedTime',
        ),
    ]
