# Generated by Django 4.2.3 on 2023-09-30 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_remove_createtodo_createddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtodo',
            name='createdDT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(auto_now_add = True),
        ),
        migrations.AddField(
            model_name='createtodo',
            name='expectedTime',
            field=models.TimeField(auto_now_add = True),
        ),
    ]
