# Generated by Django 4.2.3 on 2023-09-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_createtodo_createddt_createtodo_expecteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtodo',
            name='createdDT',
            field=models.DateTimeField(auto_now_add = True),
        ),
    ]
