# Generated by Django 4.2.3 on 2023-09-30 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_createtodo_createddt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='createdDT',
        ),
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedTime',
        ),
        migrations.AddField(
            model_name='createtodo',
            name='crateDt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
