# Generated by Django 4.2.3 on 2023-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_remove_createtodo_createddt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtodo',
            name='crateDt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='expectedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
