# Generated by Django 4.2.3 on 2023-09-30 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_createtodo_cratedt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='expectedDate',
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='crateDt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
