# Generated by Django 4.2.3 on 2023-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_remove_createtodo_expecteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtodo',
            name='crateDt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
